import Logo from "@/assets/images/logo.png";

import IcoCoin from "@/assets/icon/coin.png";
import IcoBack from "@/assets/icon/back.png";
import IcoCollect from "@/assets/icon/collection.png";
import IcoCollectBd from "@/assets/icon/collection-bd.png";
import IcoChart from "@/assets/icon/chart.png";
import IcoFootball from "@/assets/icon/football.png";
import IcoUp from "@/assets/icon/up.png";
import IcoSearch from "@/assets/icon/search.png";

import Like from "@/assets/icon/like.png";
import UnLike from "@/assets/icon/unlike.png";
import Share from "@/assets/icon/share.png";
import Report from "@/assets/icon/report.png";

import IcoFriend from "@/assets/icon/friend.png";
import IcoEyeOpen from "@/assets/icon/eye-open.png";
import IcoEyeClose from "@/assets/icon/eye-close.png";
import IcoCopy from "@/assets/icon/copy.png";
import IcoRefresh from "@/assets/icon/refresh.png";
import IcoTran from "@/assets/icon/tran.png";
import IcoDgx from "@/assets/icon/dgx.png";
import IcoEth from "@/assets/icon/eth.png";
import IcoSol from "@/assets/icon/sol.png";
import IcoUsdt from "@/assets/icon/usdt.png";

import BarAccount from "@/assets/bar/account.png";
import BarCasino from "@/assets/bar/casino.png";
import BarEsports from "@/assets/bar/esports.png";
import BarGames from "@/assets/bar/games.png";
import BarPredict from "@/assets/bar/predict.png";
import BarSports from "@/assets/bar/sports.png";

import NewGamesImg16 from "@/assets/games/new-games16.png";
import NewGamesImg15 from "@/assets/games/new-games15.png";
import NewGamesImg06 from "@/assets/games/new-games06.png";
import NewGamesImg07 from "@/assets/games/new-games07.png";
import NewGamesImg08 from "@/assets/games/new-games08.png";
import NewGamesImg05 from "@/assets/games/new-games05.png";
import NewGamesImg04 from "@/assets/games/new-games04.png";
import NewGamesImg01 from "@/assets/games/new-games01.png";
import NewGamesImg03 from "@/assets/games/new-games03.png";
import NewGamesImg02 from "@/assets/games/new-games02.png";

export default {
	logo: Logo,
	ico: {
		coin: IcoCoin,
		back: IcoBack,
		collect: IcoCollect,
		collectBd: IcoCollectBd,
		chart: IcoChart,
		football: IcoFootball,
		up: IcoUp,
		like: Like,
		unLike: UnLike,
		share: Share,
		report: Report,
		friend: IcoFriend,
		eyeOpen: IcoEyeOpen,
		eyeClose: IcoEyeClose,
		copy: IcoCopy,
		refresh: IcoRefresh,
		tran: IcoTran,
		dgx: IcoDgx,
		eth: IcoEth,
		sol: IcoSol,
		usdt: IcoUsdt,
		search: IcoSearch,
	},
	bar: {
		casino: BarCasino,
		account: BarAccount,
		esports: BarEsports,
		games: BarGames,
		predict: BarPredict,
		sports: BarSports,
	},
	gameToken1: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE0NjAxMTk3ODU1MTcwODg3NjgiLCJlbWFpbCI6IjcxNDcyMTdAMTYzLmNvbSIsInBob25lIjoiMTg2LTE4MjExMDIxOTAyIiwiaWF0IjoxNzM4ODI3MzU2LCJleHAiOjE3NDE0MTkzNTZ9.z59114J50K1P6xAmgvVUFJy-55qZi94ZQV-TNBYH9oA",
	casinoTop: [
		{
			id: 2,
			img: NewGamesImg16,
			title: "Slot Machine",
			key: "SlotMachine",
			desc: "Slot Machine is a tournament in the future where teams build robots to compete for fame, glory and cash prizes. In the year 2048, it has become the most popular spectator sport in the galaxy — drawing engineers, scientists and designers from all over the universe to match using their skills and wit. Each season, gamers compete for a grand jackpot prize with the chance to win other prizes and trophies along the way.",
			url: `true`,
			isLike: false,
			love: 36,
			view: "36",
		},
	],
	casinoHot: [
		{
			id: 3,
			img: NewGamesImg15,
			title: "Dice",
			key: "Dice",
			desc: "looticrous",
			view: "1238",
			love: "560",
			url: `true`,
			isLike: false,
		},
		{
			id: 4,
			img: NewGamesImg06,
			title: "Mines",
			key: "Mines",
			desc: "looticrous",
			view: "983",
			love: "306",
			url: `true`,
			isLike: false,
		},
		{
			id: 5,
			img: NewGamesImg07,
			title: "Dreamcatcher",
			key: "Dreamcatcher",
			desc: "lucasneryoficial",
			view: "480",
			love: "11",
			url: `true`,
			isLike: false,
		},
		{
			id: 6,
			img: NewGamesImg08,
			title: "Jujuraider",
			key: "Jujuraider",
			desc: "lucasneryoficial",
			view: "480",
			love: "11",
			url: `true`,
			isLike: false,
		},
	],
	gamesTop: [
		{
			id: 7,
			img: NewGamesImg05,
			title: "Cloud Chaser",
			key: "SlotMachine",
			desc: "Slot Machine is a tournament in the future where teams build robots to compete for fame, glory and cash prizes. In the year 2048, it has become the most popular spectator sport in the galaxy — drawing engineers, scientists and designers from all over the universe to match using their skills and wit. Each season, gamers compete for a grand jackpot prize with the chance to win other prizes and trophies along the way.",
			url: `true`,
			isLike: false,
			love: 36,
			view: "36",
		},
	],
	gamesHot: [
		{
			id: 8,
			img: NewGamesImg01,
			title: "Dreamcatcher",
			key: "Dreamcatcher",
			desc: "lucasneryoficial",
			view: "1238",
			love: "560",
			url: `true`,
			isLike: false,
		},
		{
			id: 9,
			img: NewGamesImg04,
			title: "Gemfruit",
			key: "Gemfruit",
			desc: "lucasneryoficial",
			view: "983",
			love: "306",
			url: `true`,
			isLike: false,
		},
		{
			id: 10,
			img: NewGamesImg03,
			title: "Dreamcatcher",
			key: "Dreamcatcher",
			desc: "lucasneryoficial",
			view: "480",
			love: "11",
			url: `true`,
			isLike: false,
		},
		{
			id: 11,
			img: NewGamesImg02,
			title: "Jujuraider",
			key: "Jujuraider",
			desc: "lucasneryoficial",
			view: "480",
			love: "11",
			url: `true`,
			isLike: false,
		},
	],
	gameDetail: [
		{
			id: 2,
			img: NewGamesImg16,
			title: "Slot Machine",
			titleSub: "XXXXXXX",
			key: "SlotMachine",
			desc: "Slot Machine is a tournament in the future where teams build robots to compete for fame, glory and cash prizes. In the year 2048, it has become the most popular spectator sport in the galaxy — drawing engineers, scientists and designers from all over the universe to match using their skills and wit. Each season, gamers compete for a grand jackpot prize with the chance to win other prizes and trophies along the way.",
			url: 'https://gamecenter.tokenation.fi/sgw/',
			isLike: true,
			love: 36,
			view: "36",
			rating: "87 (18,910 votes)",
			developer: "AM",
			released: "May 2024",
			technology: "HTML5",
			platform: "Browser (desktop, mobile, tablet)",
			classification: "Games»Casino»Slot Machine",
			tags: ["XXXXXXX", "XXXX", "XXXXXXX", "XXXXXXXX"],
		},
		{
			id: 3,
			img: NewGamesImg15,
			title: "Dice",
			titleSub: "XXXXXXX",
			key: "Dice",
			desc: "Slot Machine is a tournament in the future where teams build robots to compete for fame, glory and cash prizes. In the year 2048, it has become the most popular spectator sport in the galaxy — drawing engineers, scientists and designers from all over the universe to match using their skills and wit. Each season, gamers compete for a grand jackpot prize with the chance to win other prizes and trophies along the way.",
			url: null,
			isLike: false,
			love: 10,
			view: "36",
			rating: "87 (18,910 votes)",
			developer: "AM",
			released: "May 2024",
			technology: "HTML5",
			platform: "Browser (desktop, mobile, tablet)",
			classification: "Games»Casino»Slot Machine",
			tags: ["XXXXXXX", "XXXX", "XXXXXXX", "XXXXXXXX"],
		},
		{
			id: 4,
			img: NewGamesImg06,
			title: "Mines",
			titleSub: "XXXXXXX",
			key: "Mines",
			desc: "Slot Machine is a tournament in the future where teams build robots to compete for fame, glory and cash prizes. In the year 2048, it has become the most popular spectator sport in the galaxy — drawing engineers, scientists and designers from all over the universe to match using their skills and wit. Each season, gamers compete for a grand jackpot prize with the chance to win other prizes and trophies along the way.",
			url: null,
			isLike: true,
			love: 45,
			view: "36",
			rating: "87 (18,910 votes)",
			developer: "AM",
			released: "May 2024",
			technology: "HTML5",
			platform: "Browser (desktop, mobile, tablet)",
			classification: "Games»Casino»Slot Machine",
			tags: ["XXXXXXX", "XXXX", "XXXXXXX", "XXXXXXXX"],
		},
		{
			id: 5,
			img: NewGamesImg07,
			title: "Dreamcatcher",
			titleSub: "XXXXXXX",
			key: "Dreamcatcher",
			desc: "Slot Machine is a tournament in the future where teams build robots to compete for fame, glory and cash prizes. In the year 2048, it has become the most popular spectator sport in the galaxy — drawing engineers, scientists and designers from all over the universe to match using their skills and wit. Each season, gamers compete for a grand jackpot prize with the chance to win other prizes and trophies along the way.",
			url: 'https://gamecenter.tokenation.fi/bjw/',
			isLike: false,
			love: 0,
			view: "36",
			rating: "87 (18,910 votes)",
			developer: "AM",
			released: "May 2024",
			technology: "HTML5",
			platform: "Browser (desktop, mobile, tablet)",
			classification: "Games»Casino»Slot Machine",
			tags: ["XXXXXXX", "XXXX", "XXXXXXX", "XXXXXXXX"],
		},
		{
			id: 6,
			img: NewGamesImg08,
			title: "Jujuraider",
			titleSub: "XXXXXXX",
			key: "Jujuraider",
			desc: "Slot Machine is a tournament in the future where teams build robots to compete for fame, glory and cash prizes. In the year 2048, it has become the most popular spectator sport in the galaxy — drawing engineers, scientists and designers from all over the universe to match using their skills and wit. Each season, gamers compete for a grand jackpot prize with the chance to win other prizes and trophies along the way.",
			url: null,
			isLike: true,
			love: 27,
			view: "36",
			rating: "87 (18,910 votes)",
			developer: "AM",
			released: "May 2024",
			technology: "HTML5",
			platform: "Browser (desktop, mobile, tablet)",
			classification: "Games»Casino»Slot Machine",
			tags: ["XXXXXXX", "XXXX", "XXXXXXX", "XXXXXXXX"],
		},
		{
			id: 7,
			img: NewGamesImg05,
			title: "Cloud Chaser",
			titleSub: "XXXXXXX",
			key: "CloudChaser",
			desc: "Slot Machine is a tournament in the future where teams build robots to compete for fame, glory and cash prizes. In the year 2048, it has become the most popular spectator sport in the galaxy — drawing engineers, scientists and designers from all over the universe to match using their skills and wit. Each season, gamers compete for a grand jackpot prize with the chance to win other prizes and trophies along the way.",
			url: null,
			isLike: true,
			love: 67,
			view: "36",
			rating: "87 (18,910 votes)",
			developer: "AM",
			released: "May 2024",
			technology: "HTML5",
			platform: "Browser (desktop, mobile, tablet)",
			classification: "Games»Casino»Slot Machine",
			tags: ["XXXXXXX", "XXXX", "XXXXXXX", "XXXXXXXX"],
		},
		{
			id: 8,
			img: NewGamesImg01,
			title: "Dreamcatcher",
			titleSub: "XXXXXXX",
			key: "Dreamcatcher",
			desc: "Slot Machine is a tournament in the future where teams build robots to compete for fame, glory and cash prizes. In the year 2048, it has become the most popular spectator sport in the galaxy — drawing engineers, scientists and designers from all over the universe to match using their skills and wit. Each season, gamers compete for a grand jackpot prize with the chance to win other prizes and trophies along the way.",
			url: 'https://gamecenter.tokenation.fi/dcw/',
			isLike: false,
			love: 15,
			view: "36",
			rating: "87 (18,910 votes)",
			developer: "AM",
			released: "May 2024",
			technology: "HTML5",
			platform: "Browser (desktop, mobile, tablet)",
			classification: "Games»Casino»Slot Machine",
			tags: ["XXXXXXX", "XXXX", "XXXXXXX", "XXXXXXXX"],
		},
		{
			id: 9,
			img: NewGamesImg04,
			title: "Gemfruit",
			titleSub: "XXXXXXX",
			key: "Gemfruit",
			desc: "Slot Machine is a tournament in the future where teams build robots to compete for fame, glory and cash prizes. In the year 2048, it has become the most popular spectator sport in the galaxy — drawing engineers, scientists and designers from all over the universe to match using their skills and wit. Each season, gamers compete for a grand jackpot prize with the chance to win other prizes and trophies along the way.",
			url: 'https://gamecenter.tokenation.fi/ccw/',
			isLike: true,
			love: 32,
			view: "36",
			rating: "87 (18,910 votes)",
			developer: "AM",
			released: "May 2024",
			technology: "HTML5",
			platform: "Browser (desktop, mobile, tablet)",
			classification: "Games»Casino»Slot Machine",
			tags: ["XXXXXXX", "XXXX", "XXXXXXX", "XXXXXXXX"],
		},
		{
			id: 10,
			img: NewGamesImg03,
			title: "Dreamcatcher",
			titleSub: "XXXXXXX",
			key: "Dreamcatcher",
			desc: "Slot Machine is a tournament in the future where teams build robots to compete for fame, glory and cash prizes. In the year 2048, it has become the most popular spectator sport in the galaxy — drawing engineers, scientists and designers from all over the universe to match using their skills and wit. Each season, gamers compete for a grand jackpot prize with the chance to win other prizes and trophies along the way.",
			url: null,
			isLike: false,
			love: 12,
			view: "36",
			rating: "87 (18,910 votes)",
			developer: "AM",
			released: "May 2024",
			technology: "HTML5",
			platform: "Browser (desktop, mobile, tablet)",
			classification: "Games»Casino»Slot Machine",
			tags: ["XXXXXXX", "XXXX", "XXXXXXX", "XXXXXXXX"],
		},
		{
			id: 11,
			img: NewGamesImg02,
			title: "Jujuraider",
			titleSub: "XXXXXXX",
			key: "Jujuraider",
			desc: "Slot Machine is a tournament in the future where teams build robots to compete for fame, glory and cash prizes. In the year 2048, it has become the most popular spectator sport in the galaxy — drawing engineers, scientists and designers from all over the universe to match using their skills and wit. Each season, gamers compete for a grand jackpot prize with the chance to win other prizes and trophies along the way.",
			url: null,
			isLike: true,
			love: 57,
			view: "36",
			rating: "87 (18,910 votes)",
			developer: "AM",
			released: "May 2024",
			technology: "HTML5",
			platform: "Browser (desktop, mobile, tablet)",
			classification: "Games»Casino»Slot Machine",
			tags: ["XXXXXXX", "XXXX", "XXXXXXX", "XXXXXXXX"],
		},
	],
};
