import Video1 from "@/assets/games/running-trailer-v3.mp4";
import NewGamesImg01 from "@/assets/games/new-games01.png";
import NewGamesImg15 from "@/assets/games/new-games15.png";
import NewGamesImg16 from "@/assets/games/new-games16.png";
import NewGamesImg04 from "@/assets/games/new-games04.png";
import NewGamesImg05 from "@/assets/games/new-games05.png";
import NewGamesImg11 from "@/assets/games/new-games11.png";
import NewGamesImg12 from "@/assets/games/new-games12.png";
import NewGamesImg13 from "@/assets/games/new-games13.png";
import NewGamesImg06 from "@/assets/games/new-games06.png";
import NewGamesImg07 from "@/assets/games/new-games07.png";
import NewGamesImg08 from "@/assets/games/new-games08.png";
import NewGamesImg09 from "@/assets/games/new-games09.png";
import NewGamesImg10 from "@/assets/games/new-games10.png";
import NewGamesImg20 from "@/assets/games/new-games20.png";
import FmGh from "@/assets/games/fm-gh.png";
import FmDc from "@/assets/games/fm-dc.png";
import FmHr from "@/assets/games/fm-hr.png";
import FmAm from "@/assets/games/fm-am.png";
import NewGamesImg02 from "@/assets/games/new-games02.png";
import NewGamesImg03 from "@/assets/games/new-games03.png";

export default {
  gameToken1: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE0NjAxMTk3ODU1MTcwODg3NjgiLCJlbWFpbCI6IjcxNDcyMTdAMTYzLmNvbSIsInBob25lIjoiMTg2LTE4MjExMDIxOTAyIiwiaWF0IjoxNzM4ODI3MzU2LCJleHAiOjE3NDE0MTkzNTZ9.z59114J50K1P6xAmgvVUFJy-55qZi94ZQV-TNBYH9oA",
  gameHomeBan: [{
    id: 1,
    img: NewGamesImg01,
    v: Video1,
    title: "HexaHero",
    key: "HexaHero",
    desc: "HexaHero is a tournament in the future where teams build robots to compete for fame, glory and cash prizes. In the year 2048, it has become the most popular spectator sport in the galaxy — drawing engineers, scientists and designers from all over the universe to match using their skills and wit. Each season, gamers compete for a grand jackpot prize with the chance to win other prizes and trophies along the way.",
    url: `true`,
    isLike: false,
    love: 0,
    view: "0",
  }],
  gameHomeHot: [{
    id: 14,
    img: NewGamesImg04,
    title: "Gemfruit Harvest",
    key: "GemfruitHarvest",
    desc: "lucasneryoficial",
    view: "0",
    love: "0",
    url: `true`,
    isLike: false,
  }, {
    id: 11,
    img: NewGamesImg01,
    title: "DreamCatcher",
    key: "DreamCatcher",
    desc: "lucasneryoficial",
    view: "0",
    love: "0",
    url: `true`,
    isLike: false,
  }, {
    id: 15,
    img: NewGamesImg05,
    title: "Hexa Ringracer",
    key: "HexaRingracer",
    desc: "lucasneryoficial",
    view: "0",
    love: "0",
    url: `true`,
    isLike: false,
  }, {
    id: 10,
    img: NewGamesImg11,
    title: "AirDrop Mania",
    key: "AirDropMania",
    desc: "lucasneryoficial",
    view: "0",
    love: "0",
    url: `true`,
    isLike: false,
  }, {
    id: 16,
    img: NewGamesImg12,
    title: "Monster Planet",
    key: "Monster",
    desc: "lucasneryoficial",
    view: "0",
    love: "0",
    url: `true`,
    isLike: false,
  }, {
    id: 17,
    img: NewGamesImg13,
    title: "Hexa Arena",
    key: "HexaHero",
    desc: "lucasneryoficial",
    view: "0",
    love: "0",
    url: `true`,
    isLike: false,
  }, {
    id: 20,
    img: NewGamesImg20,
    title: "Baccarat game",
    key: "Baccaratgame",
    desc: "lucasneryoficial",
    view: "0",
    love: "0",
    url: `true`,
    isLike: false,
  }, {
    id: 19,
    img: NewGamesImg15,
    title: "Blackjack game",
    key: "Blackjackgame",
    desc: "lucasneryoficial",
    view: "0",
    love: "0",
    url: `true`,
    isLike: false,
  }, {
    id: 18,
    img: NewGamesImg16,
    title: "Slot game",
    key: "Slotgame",
    desc: "lucasneryoficial",
    view: "0",
    love: "0",
    url: `true`,
    isLike: false,
  },],
  gameHomeSon: [{
    id: 21,
    img: NewGamesImg06,
    title: "Bowmaster",
    desc: "lucasneryoficial",
    view: "0",
    love: "0",
    url: "",
    isLike: false,
  }, {
    id: 22,
    img: NewGamesImg07,
    title: "Tank Blood Fury: Mul",
    desc: "lucasneryoficial",
    view: "0",
    love: "0",
    url: "",
    isLike: false,
  }, {
    id: 23,
    img: NewGamesImg08,
    title: "Egg Up",
    desc: "lucasneryoficial",
    view: "0",
    love: "0",
    url: "",
    isLike: false,
  }, {
    id: 24,
    img: NewGamesImg09,
    title: "Merge Master Poppy B",
    desc: "lucasneryoficial",
    view: "0",
    love: "0",
    url: "",
    isLike: false,
  }, {
    id: 25,
    img: NewGamesImg10,
    title: "Skate Fun 3D",
    desc: "lucasneryoficial",
    view: "0",
    love: "0",
    url: "",
    isLike: false,
  },],
  gameDetail: [{
    id: 1,
    img: null,
    v: Video1,
    title: "HexaHero",
    titleSub: "MetaGaia Games",
    key: "HexaHero",
    desc: "HexaHero is a tournament in the future where teams build robots to compete for fame, glory and cash prizes. In the year 2048, it has become the most popular spectator sport in the galaxy — drawing engineers, scientists and designers from all over the universe to match using their skills and wit. Each season, gamers compete for a grand jackpot prize with the chance to win other prizes and trophies along the way.",
    url: `https://hexahero.metagaia.io/`,
    isLike: false,
    love: 0,
    view: "0",
    rating: "",
    developer: "MetaGaia Games",
    released: "May 2024",
    technology: "HTML5",
    platform: "Browser (desktop, mobile, tablet)",
    classification: "",
    tags: ["Games", "Turn-based", "Strategy", "Card"],
  }, {
    id: 14,
    img: FmGh,
    v: null,
    title: "Gemfruit Harvest",
    titleSub: "MetaGaia Games",
    key: "GemfruitHarvest",
    desc: "GemFruit Harvest is a classic connecting game. The goal is to connect three or more identical GemFruits. There is a time limit, so think quickly! If you get stuck, there’re tools to help you out.",
    url: `https://gamecenter.tokenation.fi/ccw/`,
    isLike: false,
    love: 0,
    view: "0",
    rating: "",
    developer: "MetaGaia Games",
    released: "May 2024",
    technology: "HTML5",
    platform: "Browser (desktop, mobile, tablet)",
    classification: "",
    tags: ["Games", "Puzzle", "Connect"],
  }, {
    id: 11,
    img: FmDc,
    v: null,
    title: "DreamCatcher",
    titleSub: "MetaGaia Games",
    key: "DreamCatcher",
    desc: "Dozing off into the adventurous dreamland and collect all the wonderful dreamcatchers for a sweet dream!",
    url: `https://gamecenter.tokenation.fi/dcw/`,
    isLike: false,
    love: 0,
    view: "0",
    rating: "",
    developer: "MetaGaia Games",
    released: "May 2024",
    technology: "HTML5",
    platform: "Browser (desktop, mobile, tablet)",
    classification: "",
    tags: ["Games", "Casual", "Action"],
  }, {
    id: 15,
    img: FmHr,
    v: null,
    title: "Hexa Ringracer",
    titleSub: "MetaGaia Games",
    key: "HexaRingracer",
    desc: "Get ready to skilfully pilot Hexa to zoom through racetrack set in the vastness of space filled",
    url: `https://gamecenter.tokenation.fi/dgw/`,
    isLike: false,
    love: 0,
    view: "0",
    rating: "",
    developer: "MetaGaia Games",
    released: "May 2024",
    technology: "HTML5",
    platform: "Browser (desktop, mobile, tablet)",
    classification: "",
    tags: ["Games", "Racing"],
  }, {
    id: 10,
    img: FmAm,
    v: null,
    title: "AirDrop Mania",
    titleSub: "MetaGaia Games",
    key: "AirDropMania",
    desc: "Merge your way to the top in this addictive puzzle game! Combine tokens to create higher-level ones and strategically plan your moves to avoid gridlock. With vibrant graphics, challenging levels, and global leaderboards, AirDrop Mania offers endless fun and brain-teasing puzzles. Can you reach the ultimate TOKENATION token? Start merging now!",
    url: `https://gamecenter.tokenation.fi/xgw/`,
    isLike: false,
    love: 0,
    view: "0",
    rating: "",
    developer: "MetaGaia Games",
    released: "May 2024",
    technology: "HTML5",
    platform: "Browser (desktop, mobile, tablet)",
    classification: "",
    tags: ["Games", "Puzzle", "Connect"],
  }, {
    id: 12,
    img: NewGamesImg02,
    v: null,
    title: "Jujuraiders",
    titleSub: "MetaGaia Games",
    key: "Jujuraiders",
    desc: "Experience the Thrill of JuJuRaiders - Where Strategy and Speed Collide! Join the fast-paced and exhilarating universe of JuJuRaiders, the latest multiplayer sensation exclusive to the MetaGaia Metaverse. In this futuristic world, strategy and action merge to create an adventure like no other. Are you ready to embark on a quest filled with excitement, challenges and endless fun?",
    url: "",
    isLike: false,
    love: 0,
    view: "0",
    rating: "",
    developer: "MetaGaia Games",
    released: "May 2024",
    technology: "HTML5",
    platform: "Browser (desktop, mobile, tablet)",
    classification: "",
    tags: ["Games", "Casual", "Multiplayer"],
  }, {
    id: 13,
    img: NewGamesImg03,
    v: null,
    title: "Maze",
    titleSub: "MetaGaia Games",
    key: "Maze",
    desc: "Maze is a fun and exciting puzzle multiplayer puzzle game. Players will be racing to the finish line through a huge number of twists and turns; collect gadgets to progress faster.",
    url: "",
    isLike: false,
    love: 0,
    view: "0",
    rating: "",
    developer: "MetaGaia Games",
    released: "May 2024",
    technology: "HTML5",
    platform: "Browser (desktop, mobile, tablet)",
    classification: "",
    tags: ["Games", "Puzzle", "Multiplayer", "Racing"],
  }, {
    id: 16,
    img: NewGamesImg12,
    v: null,
    title: "Monster Planet",
    titleSub: "MetaGaia Games",
    key: "Monster",
    desc: "Dive into the relentless action of Monster Planet, where survival is key! On this monster-infested world, you're the Hero in constant motion, fighting off endless waves of ferocious creatures. Each moment counts in this thrilling adventure!",
    url: "https://gamecenter.tokenation.fi/rgw/",
    isLike: false,
    love: 0,
    view: "0",
    rating: "",
    developer: "MetaGaia Games",
    released: "May 2024",
    technology: "HTML5",
    platform: "Browser (desktop, mobile, tablet)",
    classification: "",
    tags: ["Games", "Puzzle", "Multiplayer", "Racing"],
  }, {
    id: 17,
    img: NewGamesImg13,
    v: null,
    title: "Hexa Arena",
    titleSub: "MetaGaia Games",
    key: "HexaHero",
    desc: "Enter the exhilarating world of Hexa Arena, where you pilot powerful mechs in an all-out battle for dominance! Choose your Hexa mech and dive into intense, non-stop action as you shoot down waves of enemy mechs. Collect upgrades, enhance your firepower, and become the ultimate mech warrior. Hexa Arena offers an adrenaline-pumping experience that will keep you hooked!",
    url: "https://gamecenter.tokenation.fi/haw/",
    isLike: false,
    love: 0,
    view: "0",
    rating: "",
    developer: "MetaGaia Games",
    released: "May 2024",
    technology: "HTML5",
    platform: "Browser (desktop, mobile, tablet)",
    classification: "",
    tags: ["Games", "Puzzle", "Multiplayer", "Racing"],
  }, {
    id: 21,
    img: NewGamesImg06,
    v: null,
    title: "Bowmaster",
    titleSub: "MetaGaia Games",
    key: "Bowmaster",
    desc: "lucasneryoficial",
    url: "",
    isLike: false,
    love: 0,
    view: "0",
    rating: "",
    developer: "MetaGaia Games",
    released: "May 2024",
    technology: "HTML5",
    platform: "Browser (desktop, mobile, tablet)",
    classification: "",
    tags: ["Games", "Turn-based", "Strategy", "Card"],
  }, {
    id: 22,
    img: NewGamesImg07,
    v: null,
    title: "Tank Blood Fury: Mul",
    titleSub: "MetaGaia Games",
    key: "TankBloodFury",
    desc: "lucasneryoficial",
    url: "",
    isLike: false,
    love: 0,
    view: "0",
    rating: "",
    developer: "MetaGaia Games",
    released: "May 2024",
    technology: "HTML5",
    platform: "Browser (desktop, mobile, tablet)",
    classification: "",
    tags: ["Games", "Turn-based", "Strategy", "Card"],
  }, {
    id: 23,
    img: NewGamesImg08,
    v: null,
    title: "Egg Up",
    titleSub: "MetaGaia Games",
    key: "EggUp",
    desc: "lucasneryoficial",
    url: "",
    isLike: false,
    love: 0,
    view: "0",
    rating: "",
    developer: "MetaGaia Games",
    released: "May 2024",
    technology: "HTML5",
    platform: "Browser (desktop, mobile, tablet)",
    classification: "",
    tags: ["Games", "Turn-based", "Strategy", "Card"],
  }, {
    id: 24,
    img: NewGamesImg09,
    v: null,
    title: "Merge Master Poppy B",
    titleSub: "MetaGaia Games",
    key: "MergeMasterPoppy",
    desc: "lucasneryoficial",
    url: "",
    isLike: false,
    love: 0,
    view: "0",
    rating: "",
    developer: "MetaGaia Games",
    released: "May 2024",
    technology: "HTML5",
    platform: "Browser (desktop, mobile, tablet)",
    classification: "",
    tags: ["Games", "Turn-based", "Strategy", "Card"],
  }, {
    id: 25,
    img: NewGamesImg10,
    v: null,
    title: "Skate Fun 3D",
    titleSub: "MetaGaia Games",
    key: "SkateFun",
    desc: "lucasneryoficial",
    url: "",
    isLike: false,
    love: 0,
    view: "0",
    rating: "",
    developer: "MetaGaia Games",
    released: "May 2024",
    technology: "HTML5",
    platform: "Browser (desktop, mobile, tablet)",
    classification: "",
    tags: ["Games", "Turn-based", "Strategy", "Card"],
  }, {
    id: 19,
    img: NewGamesImg15,
    v: null,
    title: "Blackjack game",
    titleSub: "MetaGaia Games",
    key: "Blackjackgame",
    desc: "Welcome to the exciting world of multiplayer blackjack, where you can experience the thrill of the casino right in the comfort of your own home.",
    url: "https://gamecenter.tokenation.fi/bjw/",
    isLike: false,
    love: 0,
    view: "0",
    rating: "87 (18,910 votes)",
    developer: "MetaGaia Games",
    released: "Sep 2024",
    technology: "HTML5",
    platform: "Browser (desktop, mobile, tablet)",
    classification: "",
    tags: ["Games", "Cards"],
  }, {
    id: 18,
    img: NewGamesImg16,
    v: null,
    title: "Slot game",
    titleSub: "MetaGaia Games",
    key: "Slotgame",
    desc: "Find the latest slots and games bonuses. Welcome bonus, bonus daily spins and many prizes. Choose yours for a chance to win! Only at Tokenation!",
    url: "https://gamecenter.tokenation.fi/sgw/",
    isLike: false,
    love: 0,
    view: "0",
    rating: "87 (18,910 votes)",
    developer: "MetaGaia Games",
    released: "Sep 2024",
    technology: "HTML5",
    platform: "Browser (desktop, mobile, tablet)",
    classification: "",
    tags: ["Games", "Slot"],
  }, {
    id: 20,
    img: NewGamesImg20,
    v: null,
    title: "Baccarat game",
    titleSub: "MetaGaia Games",
    key: "Baccaratgame",
    desc: "Baccarat: The Classic Casino Thrill!\n Place your bets on Player, Banker, or Tie and feel the rush of every deal! Easy to play, exciting to win—join now and experience the ultimate casino classic!",
    url: "https://gamecenter.tokenation.fi/baw/",
    isLike: false,
    love: 0,
    view: "0",
    rating: "87 (18,910 votes)",
    developer: "MetaGaia Games",
    released: "Sep 2024",
    technology: "HTML5",
    platform: "Browser (desktop, mobile, tablet)",
    classification: "",
    tags: ["Games", "Baccarat"],
  }],
};
